export const Themes = {
  GLOBAL_HORIZONTAL_MARGIN: 20,
  IMAGE_SIZE: 40,

  FONT_SIZE_SMALL: 18,
  FONT_SIZE_MEDIUM: 20,
  FONT_SIZE_BIG: 20,

  BLUE_COLOR: '#006FFD',
  BLACK_COLOR: '#1E1E1E',
  GRAY_COLOR: '#EFEFEF',
  DARK_GRAY_COLOR: '#8F9098',

  BACKGROUND_LIGHT_COLOR: '#FFFFFF',
};
